### ISSUE TITLE
Update Liberica to 22

### ISSUE THREAD

**Issue by mtbadi39** [ajshastri/chocolatey-packages#4]
https://github.com/bell-sw/Liberica/releases/tag/22.0.2%2B11
Thanks.

**Comment by ajshastri** [comment]
At this time, we are only maintaining the LTS versions. If we start doing every version, it'll get extremely cumbersome.

It is in the roadmap to standardize all versions and perhaps soon after, we can have one come out for every version. Until then, just the LTS.
