### ISSUE TITLE
Corretto 17 and 21 updates

### ISSUE THREAD

**Issue by rgithubli** [ajshastri/chocolatey-packages#7]
Hi, thanks for maintaining Corretto. We just released new JDKs and see the updates in this auto update commit: https://github.com/ajshastri/chocolatey-packages/commit/c9bac3aa4570e3ec748e7d79cc5b9ba33b1d74da#diff-7c67e8c78e5d570de0628b739766492e8f4a57d11474c61726d7c22b73e42c00L4

However, for 17 and 21, it doesn't seem their versions are updated as 8 & 11 do (e.g.: missing changes to update the version number to `17.0.13.11.1` in https://github.com/ajshastri/chocolatey-packages/blob/c9bac3aa4570e3ec748e7d79cc5b9ba33b1d74da/corretto-jdk-17/corretto17jdk.nuspec#L5 and https://github.com/ajshastri/chocolatey-packages/blob/c9bac3aa4570e3ec748e7d79cc5b9ba33b1d74da/corretto-jdk-17/tools/chocolateyinstall.ps1#L4)

This makes users not able to have the latest JDKs. What's more, the checksum for 17 & 21 updated while the urls haven't been updated. It's possible to make the checksum check to fail.

Could the team help check? Thanks.

**Comment by ajshastri** [comment]
@rgithubli There seems to be something weird about the feed. I'll have to redo how I do it, I am pulling data from two different sources which is not the best idea. 

I've fixed the repo and pushed out the latest.

Thank you for catching this!
